# GDM configuration storage

[daemon]
# Uncomment the line below to force the login screen to use Xorg
#WaylandEnable=false

# Enabling Automatic Login
AutomaticLoginEnable=True
AutomaticLogin=tv-emulator

# Default session for automatic login (cage-mpv for TV mode)
DefaultSession=cage-mpv

[security]

[xdmcp]

[chooser]

[debug]
# Uncomment the line below to turn on debugging
#Enable=true