# Cycle to the next playlist folder
F12 script-binding channel-next
RIGHT script-binding channel-next
UP script-binding channel-next

# Cycle to the previous playlist folder
F11 script-binding channel-prev
LEFT script-binding channel-prev
DOWN script-binding channel-prev

ENTER cycle pause

# Optional: Refresh the list if you added new folders while MPV was running
F5 script-binding channel-refresh
